import type {
  GlossaryEntry,
  GlossaryOccurrence,
  GlossaryVariantKind,
  GlossaryWordplayHypothesis,
} from '../../core/glossary/models';

export interface GlossaryDemoVariant {
  readonly variantId: string;
  readonly sourceForm: string;
  readonly chineseForm: string;
  readonly kind: GlossaryVariantKind;
  readonly kindLabel: string;
  readonly direction: string;
  readonly scopeSummary: string;
  readonly evidenceId: string;
  readonly annotation: 'none' | 'first-occurrence' | 'pending';
}

export interface GlossaryDemoEvidence extends GlossaryOccurrence {
  readonly location: string;
  readonly speakerLabel?: string;
  readonly targetLabel?: string;
  readonly sceneLabel: string;
  readonly translationStatusLabel: string;
  readonly use: string;
}

export interface GlossaryDemoItem {
  readonly entry: GlossaryEntry;
  readonly categoryLabel: string;
  readonly statusLabel: string;
  readonly candidates: readonly string[];
  readonly warning?: string;
  readonly variants: readonly GlossaryDemoVariant[];
  readonly wordplays: readonly GlossaryWordplayHypothesis[];
  readonly evidence: readonly GlossaryDemoEvidence[];
  readonly reviewRoute: {
    readonly kind: 'confirmed' | 'excluded' | 'model-review' | 'human';
    readonly label: string;
    readonly reason: string;
  };
}

export const GLOSSARY_DEMO_ITEMS: readonly GlossaryDemoItem[] = [
  {
    entry: {
      entryId: 'demo-seki',
      sourceTerm: '関',
      sourceAliases: ['セキ'],
      canonicalChinese: '关',
      category: 'character',
      referentKind: 'person',
      gender: {
        value: 'female',
        confidence: 'confirmed',
        evidenceIds: ['fact-seki-gender-01'],
        readerKnownFromParagraphId: '第一章 §003',
        note: '全书人物证据已确认；只用于消歧，不授权在原文缺失时添加“她”。',
      },
      senseSummary: '角色姓氏；基础条目只固定身份，不直接规定每一次称呼。',
      pronunciation: 'せき',
      status: 'locked',
      origin: 'manual',
      occurrenceCount: 37,
      firstSeenParagraphId: '第一章 §012',
      lastSeenParagraphId: '终章 §084',
      confidence: 'confirmed',
      evidenceIds: ['ev-seki-01', 'ev-seki-02', 'ev-seki-03'],
      exactMatch: true,
    },
    categoryLabel: '角色姓名',
    statusLabel: '已锁定',
    candidates: ['关', '阿关'],
    variants: [
      {
        variantId: 'demo-seki-san',
        sourceForm: '関さん',
        chineseForm: '关同学',
        kind: 'honorific',
        kindLabel: '正式称呼',
        direction: '角色 A → 关',
        scopeSummary: '初识阶段 · 教室公开场合 · 原文明示「さん」',
        evidenceId: 'ev-seki-01',
        annotation: 'none',
      },
      {
        variantId: 'demo-seki-chan',
        sourceForm: '関ちゃん',
        chineseForm: '小关',
        kind: 'nickname',
        kindLabel: '亲昵称呼',
        direction: '角色 A → 关',
        scopeSummary: '熟识阶段 · 私下轻松场景 · 原文明示「ちゃん」',
        evidenceId: 'ev-seki-02',
        annotation: 'none',
      },
      {
        variantId: 'demo-seki-kun-long',
        sourceForm: '関くーん',
        chineseForm: '关——君',
        kind: 'teasing-name',
        kindLabel: '打趣称呼',
        direction: '角色 A → 关',
        scopeSummary: '熟识阶段 · 打趣氛围 · 保留原文拖长音，不推断额外事实',
        evidenceId: 'ev-seki-03',
        annotation: 'first-occurrence',
      },
    ],
    wordplays: [],
    evidence: [
      {
        occurrenceId: 'ev-seki-01',
        entryId: 'demo-seki',
        chapterId: 'chapter-1',
        paragraphId: '第一章 §012',
        sourceForm: '関さん',
        location: '第一章 §012 · 初次正式交谈',
        japaneseExcerpt: '「関さん、こちらへどうぞ」',
        translatedChineseExcerpt: '“关同学，请到这边来。”',
        renderedChineseForm: '关同学',
        translationStatus: 'human-edited',
        translationCandidateId: 'demo-translation-seki-01',
        speakerId: 'character-a',
        targetId: 'demo-seki',
        sceneId: 'scene-classroom-formal',
        relationshipStageId: 'newly-met',
        atmosphereTags: ['formal', 'public'],
        matchedVariantId: 'demo-seki-san',
        confidence: 'confirmed',
        speakerLabel: '角色 A',
        targetLabel: '关',
        sceneLabel: '初识阶段 · 教室公开场合',
        translationStatusLabel: '人工修订稿',
        use: '证明原文含敬称；只约束这一类原文形式和场景。',
      },
      {
        occurrenceId: 'ev-seki-02',
        entryId: 'demo-seki',
        chapterId: 'chapter-6',
        paragraphId: '第六章 §044',
        sourceForm: '関ちゃん',
        location: '第六章 §044 · 私下催促',
        japaneseExcerpt: '「関ちゃん、早く。置いていくよ」',
        translatedChineseExcerpt: '“小关，快点。我要丢下你咯。”',
        renderedChineseForm: '小关',
        translationStatus: 'machine-draft',
        translationCandidateId: 'demo-translation-seki-02',
        speakerId: 'character-a',
        targetId: 'demo-seki',
        sceneId: 'scene-private-hurry',
        relationshipStageId: 'familiar',
        atmosphereTags: ['private', 'light'],
        matchedVariantId: 'demo-seki-chan',
        confidence: 'high',
        speakerLabel: '角色 A',
        targetLabel: '关',
        sceneLabel: '熟识阶段 · 私下轻松场景',
        translationStatusLabel: '机器草稿 · 未批准',
        use: '证明熟识阶段出现亲昵称呼；不反推所有场合都应使用昵称。',
      },
      {
        occurrenceId: 'ev-seki-03',
        entryId: 'demo-seki',
        chapterId: 'chapter-9',
        paragraphId: '第九章 §018',
        sourceForm: 'せーきーくーん',
        location: '第九章 §018 · 打趣场景',
        japaneseExcerpt: '「せーきーくーん、聞いてる？」',
        translatedChineseExcerpt: '“关——君，你有在听吗？”',
        renderedChineseForm: '关——君',
        translationStatus: 'approved',
        translationCandidateId: 'demo-translation-seki-03',
        speakerId: 'character-a',
        targetId: 'demo-seki',
        sceneId: 'scene-teasing',
        relationshipStageId: 'familiar',
        atmosphereTags: ['teasing'],
        matchedVariantId: 'demo-seki-kun-long',
        confidence: 'confirmed',
        speakerLabel: '角色 A',
        targetLabel: '关',
        sceneLabel: '熟识阶段 · 打趣氛围',
        translationStatusLabel: '已批准译文',
        use: '证明拖长音和打趣语气；注释内容不得超出当前段落可知信息。',
      },
    ],
    reviewRoute: {
      kind: 'confirmed',
      label: '已锁定',
      reason: '姓名身份和三种称呼形式已有相互一致的全书证据。',
    },
  },
  {
    entry: {
      entryId: 'demo-inori',
      sourceTerm: '祈',
      sourceAliases: [],
      canonicalChinese: '祈',
      category: 'character',
      referentKind: 'person',
      gender: {
        value: 'unknown',
        confidence: 'high',
        evidenceIds: [],
        note: '姓名和当前证据不足以判断；继续保持未知。',
      },
      senseSummary: '角色姓名；同形译名待结合读音与全书自我介绍证据确认。',
      pronunciation: 'いのり',
      status: 'review',
      origin: 'ai-extracted',
      occurrenceCount: 45,
      firstSeenParagraphId: '序章 §006',
      lastSeenParagraphId: '终章 §091',
      confidence: 'high',
      evidenceIds: ['ev-inori-01', 'ev-inori-02'],
      exactMatch: true,
    },
    categoryLabel: '角色姓名',
    statusLabel: '待确认',
    candidates: ['祈', '伊祈'],
    warning: '基础译名未锁定；所有候选在人工确认前都不会传给翻译工位。',
    variants: [
      {
        variantId: 'demo-inori-chan',
        sourceForm: '祈ちゃん',
        chineseForm: '小祈',
        kind: 'nickname',
        kindLabel: '亲昵称呼',
        direction: '关 → 祈',
        scopeSummary: '仅作结构示例：需由实际原文、关系阶段和场景共同确认',
        evidenceId: 'ev-inori-02',
        annotation: 'pending',
      },
    ],
    wordplays: [],
    evidence: [
      {
        occurrenceId: 'ev-inori-01',
        entryId: 'demo-inori',
        chapterId: 'prologue',
        paragraphId: '序章 §006',
        sourceForm: '祈',
        location: '序章 §006 · 自我介绍',
        japaneseExcerpt: '「祈。いのりって読むの」',
        translatedChineseExcerpt: '“祈。读作伊诺里。”',
        renderedChineseForm: '祈',
        translationStatus: 'machine-draft',
        translationCandidateId: 'demo-translation-inori-01',
        speakerId: 'demo-inori',
        sceneId: 'scene-self-introduction',
        relationshipStageId: 'first-meeting',
        atmosphereTags: ['neutral'],
        confidence: 'high',
        speakerLabel: '祈',
        sceneLabel: '首次登场 · 自我介绍',
        translationStatusLabel: '机器草稿 · 未批准',
        use: '为读音和身份提供直接证据，不授权在别处补写姓名。',
      },
      {
        occurrenceId: 'ev-inori-02',
        entryId: 'demo-inori',
        chapterId: 'chapter-5',
        paragraphId: '第五章 §071',
        sourceForm: '祈ちゃん',
        location: '第五章 §071 · 对话',
        japaneseExcerpt: '「祈ちゃんは、どう思う？」',
        translatedChineseExcerpt: '“小祈觉得呢？”',
        renderedChineseForm: '小祈',
        translationStatus: 'human-edited',
        translationCandidateId: 'demo-translation-inori-02',
        speakerId: 'demo-seki',
        targetId: 'demo-inori',
        sceneId: 'scene-private-question',
        relationshipStageId: 'familiar',
        atmosphereTags: ['private', 'gentle'],
        matchedVariantId: 'demo-inori-chan',
        confidence: 'high',
        speakerLabel: '关',
        targetLabel: '祈',
        sceneLabel: '熟识阶段 · 私下询问',
        translationStatusLabel: '人工修订稿',
        use: '只说明这一处原文明示亲昵称呼；中文形式仍需用户确认。',
      },
    ],
    reviewRoute: {
      kind: 'model-review',
      label: '模型复核中',
      reason: '先核对读音、自我介绍和全书同名实体；暂不占用人工队列。',
    },
  },
  {
    entry: {
      entryId: 'demo-qifan',
      sourceTerm: '祁帆',
      sourceAliases: ['チーファン'],
      canonicalChinese: '祁帆',
      category: 'character',
      referentKind: 'person',
      gender: {
        value: 'unknown',
        confidence: 'high',
        evidenceIds: [],
        note: '姓名不能作为性别证据；全书尚无可靠明示。',
      },
      senseSummary: '人物姓名；后文把读音听成“喜欢”，属于跨段落回收的姓名谐音。',
      pronunciation: 'チーファン',
      status: 'review',
      origin: 'ai-extracted',
      occurrenceCount: 18,
      firstSeenParagraphId: '第二章 §021',
      lastSeenParagraphId: '第十一章 §063',
      confidence: 'high',
      evidenceIds: ['ev-qifan-01', 'ev-qifan-02'],
      exactMatch: true,
    },
    categoryLabel: '角色姓名',
    statusLabel: '待你决定',
    candidates: ['祁帆'],
    variants: [
      {
        variantId: 'demo-qifan-homophone',
        sourceForm: '好き',
        chineseForm: '喜欢',
        kind: 'phonetic-wordplay',
        kindLabel: '姓名谐音',
        direction: '真琴 → 祁帆',
        scopeSummary: '后文明确把姓名读音与「好き」联系起来；不是普通别名，也不能只看首次出场判断。',
        evidenceId: 'ev-qifan-02',
        annotation: 'pending',
      },
    ],
    wordplays: [
      {
        hypothesisId: 'wordplay-qifan-like',
        entryId: 'demo-qifan',
        kind: 'near-homophone',
        sourceForm: '祁帆 / チーファン',
        heardOrAlternateForm: '好き',
        sourceReading: 'チーファン',
        alternateReading: 'すき',
        narrativeMeaning: '人物把姓名听成“喜欢”，后续感情线再次回收这次误读。',
        evidenceIds: ['ev-qifan-01', 'ev-qifan-02', 'event-qifan-ch11-callback'],
        counterEvidenceIds: [],
        proposedChineseRenderings: [
          '保留“祁帆”，在台词中直写“听起来像‘喜欢’”',
          '保留“祁帆”，在第一次误读处加一条简短注释',
          '结合后续回收方式调整姓名译字，使中文读音也能形成谐音',
        ],
        annotationRecommended: true,
        readerKnowledgeStatus: 'needs-review',
        confidence: 'high',
        status: 'review',
      },
    ],
    evidence: [
      {
        occurrenceId: 'ev-qifan-01',
        entryId: 'demo-qifan',
        chapterId: 'chapter-2',
        paragraphId: '第二章 §021',
        sourceForm: '祁帆',
        location: '第二章 §021 · 自我介绍',
        japaneseExcerpt: '「祁帆。チーファンって読む」',
        translatedChineseExcerpt: '“祁帆，读作祁帆。”',
        renderedChineseForm: '祁帆',
        translationStatus: 'machine-draft',
        translationCandidateId: 'demo-translation-qifan-01',
        speakerId: 'demo-qifan',
        sceneId: 'scene-qifan-introduction',
        relationshipStageId: 'first-meeting',
        atmosphereTags: ['neutral'],
        confidence: 'high',
        speakerLabel: '祁帆',
        sceneLabel: '首次见面 · 自我介绍',
        translationStatusLabel: '机器草稿',
        use: '只看这里能够确认姓名与读音，还看不出后文会用它构成谐音。',
      },
      {
        occurrenceId: 'ev-qifan-02',
        entryId: 'demo-qifan',
        chapterId: 'chapter-4',
        paragraphId: '第四章 §038',
        sourceForm: 'チーファン',
        location: '第四章 §038 · 误读姓名',
        japaneseExcerpt: '「チーファンって、好きって聞こえるね」',
        translatedChineseExcerpt: '“祁帆听起来很像‘喜欢’呢。”',
        renderedChineseForm: '祁帆 / 喜欢',
        translationStatus: 'human-edited',
        translationCandidateId: 'demo-translation-qifan-02',
        speakerId: 'character-makoto',
        targetId: 'demo-qifan',
        sceneId: 'scene-qifan-wordplay',
        relationshipStageId: 'acquainted',
        atmosphereTags: ['teasing', 'foreshadowing'],
        matchedVariantId: 'demo-qifan-homophone',
        confidence: 'confirmed',
        speakerLabel: '真琴',
        targetLabel: '祁帆',
        sceneLabel: '熟识前期 · 姓名误读',
        translationStatusLabel: '人工修订稿',
        use: '直接证明谐音存在；第十一章的感情线回收决定它不能被当作随口玩笑丢掉。',
      },
    ],
    reviewRoute: {
      kind: 'human',
      label: '待你决定',
      reason: '谐音已经由模型找到并核实；仍有三种都忠实但阅读效果不同的中文处理。',
    },
  },
  {
    entry: {
      entryId: 'demo-organization-long',
      sourceTerm: '北宇治高等学校吹奏楽部コンクールメンバー選考会',
      sourceAliases: ['北宇治吹奏楽部'],
      canonicalChinese: '北宇治高中吹奏乐部竞赛成员选拔会',
      category: 'organization',
      referentKind: 'event',
      gender: {
        value: 'not-applicable',
        confidence: 'confirmed',
        evidenceIds: [],
        note: '活动名称。',
      },
      senseSummary: '活动与组织复合专名；需要检查是否应拆为“组织名 + 活动名”。',
      status: 'conflict',
      origin: 'ai-extracted',
      occurrenceCount: 3,
      firstSeenParagraphId: '第三章 §009',
      confidence: 'medium',
      evidenceIds: ['ev-long-01'],
      exactMatch: true,
    },
    categoryLabel: '组织 / 活动',
    statusLabel: '有冲突',
    candidates: ['北宇治高中吹奏乐部竞赛成员选拔会', '北宇治高中吹奏乐部·竞赛阵容选拔'],
    warning: '复合词疑似应拆分。冲突解决前不会进行全书强制映射。',
    variants: [],
    wordplays: [],
    evidence: [
      {
        occurrenceId: 'ev-long-01',
        entryId: 'demo-organization-long',
        chapterId: 'chapter-3',
        paragraphId: '第三章 §009',
        sourceForm: '北宇治高等学校吹奏楽部コンクールメンバー選考会',
        location: '第三章 §009 · 章节标题',
        japaneseExcerpt: '北宇治高等学校吹奏楽部コンクールメンバー選考会',
        translatedChineseExcerpt: '北宇治高中吹奏乐部竞赛成员选拔会',
        renderedChineseForm: '北宇治高中吹奏乐部竞赛成员选拔会',
        translationStatus: 'machine-draft',
        translationCandidateId: 'demo-translation-long-01',
        sceneId: 'scene-chapter-title',
        atmosphereTags: ['chapter-title'],
        confidence: 'medium',
        sceneLabel: '章节标题 · 复合专名',
        translationStatusLabel: '机器草稿 · 未批准',
        use: '完整长名称用于检查拆分边界和 EPUB 标题结构。',
      },
    ],
    reviewRoute: {
      kind: 'model-review',
      label: '拆词复核中',
      reason: '先由专名工位比较“组织名 + 活动名”的拆分结果；只有模型仍分歧才转人工。',
    },
  },
  {
    entry: {
      entryId: 'demo-common-word',
      sourceTerm: '春',
      sourceAliases: [],
      canonicalChinese: '春天',
      category: 'concept',
      referentKind: 'concept',
      gender: {
        value: 'not-applicable',
        confidence: 'confirmed',
        evidenceIds: [],
        note: '普通叙述词。',
      },
      senseSummary: '普通词，并非稳定专名。',
      status: 'rejected',
      origin: 'ai-extracted',
      occurrenceCount: 62,
      firstSeenParagraphId: '第一章 §001',
      confidence: 'high',
      evidenceIds: ['ev-spring-01'],
      exactMatch: false,
    },
    categoryLabel: '普通词',
    statusLabel: '已排除',
    candidates: ['春天'],
    warning: '高频不等于术语。普通词不进入强制术语表，以免破坏上下文翻译。',
    variants: [],
    wordplays: [],
    evidence: [
      {
        occurrenceId: 'ev-spring-01',
        entryId: 'demo-common-word',
        chapterId: 'chapter-1',
        paragraphId: '第一章 §001',
        sourceForm: '春',
        location: '第一章 §001 · 叙述',
        japaneseExcerpt: '春の風が窓から入り込んだ。',
        translatedChineseExcerpt: '春风从窗外吹了进来。',
        renderedChineseForm: '春',
        translationStatus: 'human-edited',
        translationCandidateId: 'demo-translation-spring-01',
        sceneId: 'scene-opening-narration',
        atmosphereTags: ['narration'],
        confidence: 'high',
        sceneLabel: '开篇叙述 · 普通词语境',
        translationStatusLabel: '人工修订稿',
        use: '用于证明这是普通叙述用词，应从术语候选中排除。',
      },
    ],
    reviewRoute: {
      kind: 'excluded',
      label: '自动排除',
      reason: '全书用法均为普通季节词，不具备稳定专名身份。',
    },
  },
] as const;
